/**
 * Rewrites the stored `Room.images` paths to the descriptive filenames.
 *
 * The photo library used to live in camera-named folders that were also the
 * public URLs:
 *
 *   /1. ground floor No1/MTS_0729.jpg
 *   /FRONT VIEW/NZ6_5387-Edit-3.jpg
 *
 * The public site has moved the files to
 * `/images/<context>/lincanto-<context>-preveza-NN.jpg` and currently
 * translates old -> new at render time, so this migration is optional and the
 * site works either way. Running it removes the translation layer's reason to
 * exist and makes the database agree with the URLs being published.
 *
 * `scripts/image-map.json` is generated by `scripts/rename-images.js` in
 * stefanos-licanto — regenerate it there rather than editing it here.
 *
 * Idempotent: paths that are already descriptive, or that were never part of
 * the library (Cloudinary uploads, the logo), are left alone.
 *
 *   pnpm tsx scripts/rename-room-images.ts [--dry]
 */
import { PrismaClient } from '../prisma/generated/prisma/client';
import { PrismaLibSql } from '@prisma/adapter-libsql';
import * as dotenv from 'dotenv';
import imageMap from './image-map.json';

dotenv.config();

const prisma = new PrismaClient({
  adapter: new PrismaLibSql({ url: process.env.DATABASE_URL! }),
});

const MAP = imageMap as Record<string, string>;

function migratePath(stored: string): string {
  if (typeof stored !== 'string' || /^https?:\/\//i.test(stored)) return stored;
  const normalized = stored.startsWith('/') ? stored : `/${stored}`;
  return MAP[normalized] ?? stored;
}

async function main() {
  const dryRun = process.argv.includes('--dry');

  const rooms = await prisma.room.findMany({
    select: { id: true, name: true, images: true },
    orderBy: { name: 'asc' },
  });

  let roomsChanged = 0;
  let pathsChanged = 0;

  for (const room of rooms) {
    const images = Array.isArray(room.images) ? (room.images as unknown[]) : [];
    if (images.length === 0) continue;

    const migrated = images.map((image) =>
      typeof image === 'string' ? migratePath(image) : image,
    );

    const changed = migrated.filter((value, index) => value !== images[index]).length;
    if (changed === 0) {
      console.log(`  skip  ${room.name} (already migrated)`);
      continue;
    }

    if (!dryRun) {
      await prisma.room.update({ where: { id: room.id }, data: { images: migrated as any } });
    }

    roomsChanged += 1;
    pathsChanged += changed;
    console.log(`  ${dryRun ? 'would' : 'set  '} ${room.name}: ${changed}/${images.length} paths`);
  }

  console.log(
    `\n${dryRun ? 'Would update' : 'Updated'} ${pathsChanged} paths across ${roomsChanged} rooms.`,
  );

  if (!dryRun && roomsChanged > 0) {
    console.log(
      '\nThe public site keeps working either way — it translates old paths at render\n' +
        'time and 301s the old image URLs. Leave those redirects in place: Google has\n' +
        'the old URLs in its image index.',
    );
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
